// import initHomeOne from "./modules/home-one.js";
import initGeral from "./modules/geral.js";
import initLive from "./modules/live.js";
import initMensagem from "./modules/mensagem.js";
import initNavMobile from "./modules/nav-mobile.js";
import initPerfil from "./modules/perfil.js";
import initModoDark from "./modules/mododark.js";
import initSideNavChose from "./modules/side-nav-chose.js";
import initCurti from "./modules/curti.js";
import initLoad from "./modules/load.js";

// initHomeOne();
initGeral();
initLive();
initMensagem();
initNavMobile();
initPerfil();
initModoDark();
initSideNavChose();
initCurti();
initLoad();
